#!/bin/bash

# ============================================================================
# NAS HELP - REDACTED_HOSTNAME_TC Cloud Platform
# ============================================================================

echo "═══════════════════════════════════════════════════════"
echo "           REDACTED_HOSTNAME_TC Cloud Platform — Help"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "📁 NAS Scripts (/mnt/nas2/nas-scripts/):"
echo "  -- stato e utilita' --"
echo "  nas_status.sh        Quick status (mount, container, SMART, cert)"
echo "  nas_info.sh          Info sistema (dinamiche)"
echo "  nas-help.sh          Questa guida"
echo "  change_password.sh   Cambio password Samba"
echo "  -- dischi e condivisioni --"
echo "  setup_disk.sh        Configura/ripara dischi (rileva via serial, idempotente)"
echo "  fix_nas.sh           Ripara fstab e rimonta (serial-based, UUID)"
echo "  setup_samba.sh       Configura Samba + Avahi + UFW"
echo "  -- riconfigurazione e host --"
echo "  setup_reconfigure.sh Riconfigura host services, cron, Samba, mail, OIDC"
echo "  setup_host_services.sh  wifi-watchdog, fixperms, docker-ensure-containers"
echo "  setup_cron.sh        Cron job gestiti (backup, certbot, cleanup)"
echo "  setup_fail2ban.sh    Hardening SSH + fail2ban"
echo "  setup_kdump.sh       kdump e panic su lockup (richiede reboot)"
echo "  setup_systemd_watchdog.sh  Alert email se PID1 e' bloccato"
echo "  cleanup_logs.sh, wifi_watchdog.sh, systemd_watchdog.sh  (lanciati da cron/timer)"
echo "  -- servizi e rete --"
echo "  setup_mail.sh        SMTP condiviso servizi (relay SMTP, REDACTED_SERVICE_EMAIL)"
echo "  setup_nextcloud_oidc.sh  Redirect URI dei client OIDC (Immich, Jellyfin, Vaultwarden)"
echo "  setup_nginx_realip.sh, setup_nginx_tls_ecdsa.sh  Patch nginx (IP reale, cifrari ECDSA)"
echo "  setup_jellyfin_sso_button.sh, setup_REDACTED_NAME_site.sh  Patch nginx (bottone SSO, sito dedicato)"
echo "  update_immich_version.sh, update_jellyfin_version.sh  Aggiornamento versioni"
echo "  setup_claude_desktop.sh  Claude Desktop e browser"
echo "  -- backup --"
echo "  backup_offsite.sh    Backup Borg offsite (cron 03:00)"
echo "  borg_backup_nas2.sh  Backup Borg NAS2 -> NAS (cron 04:00)"
echo "  backup_setup.sh, backup_restore.sh  Setup e ripristino"
echo "  setup_proton_cli_backup.sh, proton_cli_backup.sh  Mirror su Proton Drive"
echo "  incus_config_backup.sh  Backup leggero della config Incus"
echo "  -- Incus (VM) --"
echo "  setup_incus.sh       Installa/gestisce Incus, UI, proxy, storage"
echo "  incus_vm_hook.sh     Hook proxy/DNS (lanciato ogni 30s da timer)"
echo ""
echo "🐳 Docker Scripts (/mnt/nas2/docker/):"
echo "  kickstart/kickstart.sh  Bootstrap completo da server pulito"
echo "  deploy.sh         Deploy completo (kickstart SSL + stack)"
echo "  utils.sh          Utility: status, logs, restart, backup, renew, smartcheck, ..."
echo "  check.sh          Verifica configurazione"
echo ""
echo "🔧 Comandi utili:"
echo "  docker compose ps                    Stato container"
echo "  docker compose logs -f [servizio]    Log in tempo reale"
echo "  ./utils.sh status                    Status completo"
echo "  ./utils.sh smartcheck                Check SMART immediato"
echo "  ./utils.sh backup                    Backup DB Immich"
echo "  ./utils.sh renew                     Rinnova certificati SSL"
echo ""
echo "🌐 Servizi web:"
echo "  https://REDACTED_HOSTNAME.REDACTED_DDNS            Sito principale"
echo "  https://immich.REDACTED_HOSTNAME.REDACTED_DDNS     Foto (Immich)"
echo "  https://jellyfin.REDACTED_HOSTNAME.REDACTED_DDNS   Media (Jellyfin)"
echo "  https://bitwarden.REDACTED_HOSTNAME.REDACTED_DDNS  Password (Vaultwarden)"
echo "  https://webdav.REDACTED_HOSTNAME.REDACTED_DDNS     File sharing (WebDAV)"
echo "  https://syncthing.REDACTED_HOSTNAME.REDACTED_DDNS  Sync"
echo "  https://modem.REDACTED_HOSTNAME.REDACTED_DDNS      Modem admin (auth)"
echo ""
echo "📁 Samba (LAN):"
echo "  smb://$(hostname -I | awk '{print $1}')/NAS"
echo "  smb://$(hostname -I | awk '{print $1}')/NAS2"
echo "  smb://$(hostname -I | awk '{print $1}')/TimeMachine"
echo ""
echo "🔑 SSH:"
echo "  ssh REDACTED_HOSTNAME@$(hostname -I | awk '{print $1}') -p 2222"
echo ""
echo "⚠️  Note:"
echo "  - /mnt/nas e /mnt/timemachine: backup — NON modificare direttamente"
echo "  - Password Samba: sudo smbpasswd REDACTED_HOSTNAME"
echo "  - Servizi opzionali (via --profile): plex (con JellyPlex-Watched), icloud"
