#!/bin/bash

# ============================================================================
# NAS HELP - REDACTED_HOSTNAME_TC Cloud Platform
# ============================================================================

echo "═══════════════════════════════════════════════════════"
echo "           REDACTED_HOSTNAME_TC Cloud Platform — Help"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "📁 NAS Scripts (/mnt/nas2/nas-scripts/):"
echo "  setup_disk.sh     Configura/ripara dischi (rileva via serial, idempotente)"
echo "  setup_reconfigure.sh  Riconfigura host services, cron, Samba, mail, OIDC"
echo "  setup_mail.sh     SMTP condiviso servizi (REDACTED_SMTP_PROVIDER relay, REDACTED_SERVICE_EMAIL)"
echo "  fix_nas.sh        Ripara fstab e rimonta (serial-based, UUID)"
echo "  setup_samba.sh    Configura Samba + Avahi + UFW (LAN-only)"
echo "  nas_info.sh       Info sistema (dinamiche)"
echo "  nas_status.sh     Quick status (mount, container, SMART, cert)"
echo "  borg_backup_nas2.sh  Backup Borg NAS2 → NAS"
echo ""
echo "🐳 Docker Scripts (/mnt/nas2/docker/):"
echo "  deploy.sh         Deploy completo (kickstart SSL + stack)"
echo "  utils.sh          Utility: status, logs, restart, backup, renew, smartcheck, ..."
echo "  check.sh          Verifica configurazione"
echo ""
echo "🔧 Comandi utili:"
echo "  docker compose ps                    Stato container"
echo "  docker compose logs -f [servizio]    Log in tempo reale"
echo "  ./utils.sh status                    Status completo"
echo "  ./utils.sh smartcheck                Check SMART immediato"
echo "  ./utils.sh backup                    Backup DB Immich"
echo "  ./utils.sh renew                     Rinnova certificati SSL"
echo ""
echo "🌐 Servizi web:"
echo "  https://REDACTED_HOSTNAME.REDACTED_DDNS            Sito principale"
echo "  https://immich.REDACTED_HOSTNAME.REDACTED_DDNS     Foto (Immich)"
echo "  https://jellyfin.REDACTED_HOSTNAME.REDACTED_DDNS   Media (Jellyfin)"
echo "  https://bitwarden.REDACTED_HOSTNAME.REDACTED_DDNS  Password (Vaultwarden)"
echo "  https://webdav.REDACTED_HOSTNAME.REDACTED_DDNS     File sharing (WebDAV)"
echo "  https://syncthing.REDACTED_HOSTNAME.REDACTED_DDNS  Sync"
echo "  https://modem.REDACTED_HOSTNAME.REDACTED_DDNS      Modem admin (auth)"
echo ""
echo "📁 Samba (LAN):"
echo "  smb://$(hostname -I | awk '{print $1}')/NAS"
echo "  smb://$(hostname -I | awk '{print $1}')/NAS2"
echo "  smb://$(hostname -I | awk '{print $1}')/TimeMachine"
echo ""
echo "🔑 SSH:"
echo "  ssh REDACTED_HOSTNAME@$(hostname -I | awk '{print $1}') -p 2222"
echo ""
echo "⚠️  Note:"
echo "  - /mnt/nas e /mnt/timemachine: backup — NON modificare direttamente"
echo "  - Password Samba: sudo smbpasswd REDACTED_HOSTNAME"
echo "  - Servizi opzionali (via --profile): plex, jellyplex, icloud"
